# PowerGSLB configuration file

[logging]
# https://docs.python.org/3/library/logging.html
format = "%(levelname)s [%(threadName)s] %(module)s.%(funcName)s:%(lineno)d %(message)s"
level = "INFO"

[database]
# https://dev.mysql.com/doc/connector-python/en/connector-python-connectargs.html
database = "powergslb"
user = "powergslb"
password = ""
host = "127.0.0.1"
port = 3306
unix_socket = "/var/lib/mysql/mysql.sock"
connection_timeout = 1

[server]
address = "127.0.0.1"
port = 8080

[admin]
address = "0.0.0.0"
port = 443
ssl = true
cert = "/etc/powergslb/powergslb.pem"
ciphers = "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256"
#root = "/tmp/powergslb" # optional override for the admin UI document root

[monitor]
update_interval = 60
icmp_privileged = true

[geoip]
# DB-IP Lite bundled by default; override with a MaxMind GeoLite2/GeoIP2.
database = "/usr/share/powergslb/dbip-country-lite.mmdb"
